name: Build and Run Lua Test with C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone and Extract Lua Source
      run: |
        curl -L https://www.lua.org/ftp/lua-5.4.8.tar.gz -o lua.tar.gz
        mkdir lua-src
        tar -xzf lua.tar.gz -C lua-src --strip-components=1

    - name: Compile Lua with MSVC
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cd lua-src
        cl /c /O2 /DLUA_BUILD_AS_DLL ^
          src\lapi.c src\lcode.c src\lctype.c src\ldebug.c src\ldo.c src\ldump.c src\lfunc.c ^
          src\lgc.c src\llex.c src\lmem.c src\lobject.c src\lopcodes.c src\lparser.c ^
          src\lstate.c src\lstring.c src\ltable.c src\ltm.c src\lundump.c src\lvm.c ^
          src\lzio.c src\lauxlib.c src\lbaselib.c src\lcorolib.c src\ldblib.c ^
          src\liolib.c src\lmathlib.c src\loslib.c src\lstrlib.c src\ltablib.c ^
          src\lutf8lib.c src\loadlib.c src\linit.c
    
        lib /OUT:lua.lib *.obj
    
        link /DLL /OUT:lua.dll *.obj


    - name: Copy Lua output
      run: |
        mkdir lua-bin
        copy lua-src\*.dll lua-bin\
        copy lua-src\*.lib lua-bin\
    

    - name: Setup Build Environment
      shell: cmd
      run: |
        mkdir build
        copy lua-src\lua.lib build\
        copy lua-src\lua.h build\
        copy lua-src\lualib.h build\
        copy lua-src\lauxlib.h build\
        copy lua-src\lua.dll build\
    

    - name: Compile C++ Test with Lua Embedded
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" ^
        && cl lua-src\main.cpp /I build /link build\lua.lib /OUT:LuaTest.exe
    

    - name: Copy Lua Files
      run: |
        mkdir testdir
        copy lua-src\testdir\*.lua testdir\
        copy lua-src\testdir\Moo.dll testdir\

    - name: Run Executable
      run: |
        LuaTest.exe
