name: Testing API Lua
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Lua 5.4 manually
        run: |
          curl -L -o lua.zip https://sourceforge.net/projects/luabinaries/files/5.4.6/Windows%20Executables/lua-5.4.6_Win64_bin.zip/download
          tar -xf lua.zip
          echo "${{ github.workspace }}/lua-5.4.6_Win64_bin" >> $GITHUB_PATH
      

      - name: Copy required files
        run: |
          mkdir testdir
          copy api\moo.lua testdir\
          copy api\run.lua testdir\
          copy api\Moo.dll testdir\

      - name: Run Test
        run: |
          lua testdir\run.lua

      - name: Running Unit Tests (Not implemented)
        run: |
          echo "Running unit tests"