name: Testing API Python
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
      runs-on: windows-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Copy required files
        run: |
          mkdir testdir
          copy api\moo.py testdir\
          copy api\test.py testdir\
          copy api\Moo.dll testdir\
          if (exist requirements.txt) copy requirements.txt testdir\

      - name: Set up Python venv and install requirements
        run: |
          python -m venv venv
          venv\Scripts\activate
          python -m pip install --upgrade pip
          if (exist testdir\requirements.txt) pip install -r testdir\requirements.txt

      - name: Run Test
        run: |
          venv\Scripts\activate
          python testdir\test.py