name: Build and Run Lua Test with C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Lua 5.4.6
      run: |
        curl -L -o lua.tar.gz https://www.lua.org/ftp/lua-5.4.6.tar.gz
        tar -xvf lua.tar.gz
        move lua-5.4.6 lua

    - name: Setup MSVC Environment
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64

    - name: Compile Lua Core with MSVC
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" ^
        && cd lua\src ^
        && cl /c /O2 /W3 /DLUA_BUILD_AS_DLL *.c ^
        && lib /OUT:lua.lib *.obj ^
        && link /DLL /OUT:lua.dll *.obj
    

    - name: Setup Build Environment
      run: |
        mkdir build
        copy lua\src\lua.lib build\
        copy lua\src\lua.h build\
        copy lua\src\lualib.h build\
        copy lua\src\lauxlib.h build\
        copy lua\src\lua.dll build\

    - name: Compile C++ Test with Lua Embedded
      run: |
        cl src\main.cpp /I build /link build\lua.lib /OUT:LuaTest.exe

    - name: Copy Lua Files
      run: |
        mkdir testdir
        copy src\testdir\*.lua testdir\
        copy src\testdir\Moo.dll testdir\

    - name: Run Executable
      run: |
        LuaTest.exe
