name: Testing API Python
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: '5.4'

      - name: Copy required files
        run: |
          mkdir testdir
          copy api\moo.lua testdir\
          copy api\run.lua testdir\
          copy api\Moo.dll testdir\

      - name: Run Test
        run: |
          lua testdir\run.lua

      - name: Running Unit Tests (Not implemented)
        run: |
          echo "Running unit tests"