name: Testing API Python
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Copy required files
        run: |
          mkdir -p testdir
          cp api/moo.py testdir/
          cp api/test.py testdir/
          cp api/moo.dll testdir/
          if [ -f requirements.txt ]; then cp requirements.txt testdir/; fi

      - name: Set up Python venv und installiere requirements
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          if [ -f testdir/requirements.txt ]; then pip install -r testdir/requirements.txt; fi

      - name: Run Test
        run: |
          . venv/bin/activate
          python testdir/test.py