name: Compiling C++ Code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  config:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Nothing to configure
        shell: cmd
        run: |
          echo "No configuration needed for this job."

  windows:
    name: Windows+MSVC
    runs-on: windows-latest
    needs: config

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Build Environment
        shell: cmd
        run: |
          mkdir build
          copy src\*.* build\
          copy CMakeLists.txt build\

      - name: Compile C++ Code with CMAKE
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 ..
          cmake --build . --config Release

      - name: Copy Build Artifacts
        run: |
          cd ..
          mkdir artifact
          copy Moo\build\bin\Release\Moo.dll artifact\
          copy Moo\build\lib\Release\Moo.lib artifact\
          copy Moo\build\lib\Release\Moo.exp artifact\
          dir artifact
          pwd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moo-DLL-Artifacts
          path: D:\a\Moo\artifact

  windows_meson:
    name: Windows+Meson
    runs-on: windows-latest
    needs: config

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Build Environment
        shell: cmd
        run: |
          mkdir build
          copy src\*.* build\
          copy CMakeLists.txt build\

      - name: Install Meson and Ninja
        shell: cmd
        run: |
          python -m pip install meson ninja

      - name: Compile C++ Code with Meson
        shell: cmd
        run: |
          meson setup build --buildtype=release --backend=ninja
          meson compile -Cpp build

      - name: Copy Build Artifacts
        run: |
          mkdir artifact
          copy build\lib\Moo.dll artifact\
          dir artifact

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moo-DLL-Artifacts-Meson
          path: artifact\*

  unixbased:
    needs: config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vector:
          - jobname: test-debian
            image: debian:latest
            os: ubuntu-latest
            cc: gcc
          - jobname: test-ubuntu
            image: ubuntu:latest
            os: ubuntu-latest
            cc: gcc
          - jobname: test-alpine
            image: alpine:latest
            os: ubuntu-latest
            cc: gcc
          - jobname: test-fedora
            image:  fedora:latest
            os: ubuntu-latest
            cc: gcc
          - jobname: test-ubuntu-clang
            image: ubuntu:latest
            os: ubuntu-latest
            cc: clang
          - jobname: linux-sha256
            image: ubuntu:rolling
            cc: clang
          - jobname: linux-reftable
            image: ubuntu:rolling
            cc: clang
            cc_package: gcc-8
          - jobname: linux-breaking-changes
            cc: gcc
            image: ubuntu:rolling
          - jobname: linux-leaks
            image: ubuntu:rolling
            cc: gcc
          - jobname: linux-reftable-leaks
            image: ubuntu:rolling
            cc: gcc
          - jobname: linux-asan-ubsan
            image: ubuntu:rolling
            cc: clang
          - jobname: linux-meson
            image: ubuntu:rolling
            cc: gcc
          - jobname: linux-musl-meson
            image: alpine:latest
          # Supported until 2025-04-02.
          - jobname: pedantic
            image: fedora:latest
          # A RHEL 8 compatible distro.  Supported until 2029-05-31.
          - jobname: almalinux-8
            image: almalinux:8
          # Supported until 2026-08-31.
          - jobname: debian-11
            image: debian:11
    name: ${{ matrix.vector.jobname }} (${{ matrix.vector.image }})
    container: ${{ matrix.vector.image }}
    env:
      jobname: ${{ matrix.vector.jobname }}
      CC: ${{ matrix.vector.cc }}
      CI_JOB_IMAGE: ${{ matrix.vector.image }}
    steps:
      - uses: actions/checkout@v4

      - name: Build with ${{ matrix.vector.cc }} on ${{ matrix.vector.image }}
        run: echo "Building with ${{ matrix.vector.cc }} on ${{ matrix.vector.image }}"

      - name: Checking Matrix Variables
        run: |
          echo "Job Name: ${{ matrix.vector.jobname }}"
          echo "Operating System: ${{ matrix.vector.os }}"
          echo "Compiler: ${{ matrix.vector.cc }}"
          echo "Image: ${{ matrix.vector.image }}"
          if [ -z "${{ matrix.vector.cc }}" ]; then
            echo "No compiler specified, defaulting to gcc"
            echo "CC: gcc"
            echo "cc=gcc" >> $GITHUB_ENV
            echo "Using default compiler: ${{ matrix.vector.cc }}"
          else
            echo "Using compiler: ${{ matrix.vector.cc }}"
          fi

      - name: Update and Install Dependencies
        run: |
          if command -v apt-get > /dev/null; then
            apt-get update
            apt-get install -y build-essential cmake make ${{ matrix.vector.cc }}
            apt-get upgrade -y
          elif command -v apk > /dev/null; then
            apk add --no-cache build-base cmake make ${{ matrix.vector.cc }}
          elif command -v dnf > /dev/null; then
            dnf install -y gcc gcc-c++ cmake make clang
          fi

      - name: Setup Build Environment
        run: |
          mkdir -p build
          cp -r src build/

      - name: GCC Build
        if: matrix.vector.cc != 'clang' # If nothing is defined, it defaults to gcc
        run: |
          cd build/src
          gcc -Ofast -shared -o moofast.so -fPIC moo.hpp
          gcc -O3 -shared -o mooO3.so -fPIC moo.hpp
          gcc -Os -shared -o mooSize.so -fPIC moo.hpp
          gcc -Og -shared -o mooDebug.so -fPIC moo.hpp
          gcc -shared -o moo.so -fPIC moo.hpp
          ls .

      - name: Clang Build
        if: matrix.vector.cc == 'clang'
        run: |
          cd build/src
          clang -Ofast -shared -o moofast.so -fPIC moo.hpp
          clang -O3 -shared -o mooO3.so -fPIC moo.hpp
          clang -Os -shared -o mooSize.so -fPIC moo.hpp
          clang -Og -shared -o mooDebug.so -fPIC moo.hpp
          clang -shared -o moo.so -fPIC moo.hpp
          ls .

      - name: Copy Build Artifacts
        run: |
          mkdir -p artifact
          cp build/src/moo*.so artifact/
          ls artifact

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moo-SO-Artifacts-${{ matrix.vector.jobname }}
          path: artifact/*.so

  macos:
    needs: config
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update and Install Dependencies
        run: |
          brew update
          brew upgrade
          brew install cmake
          xcode-select --install || true

      - name: Setup Build Environment
        run: |
          mkdir -p build
          cp -r src build/

      - name: Compile with Clang
        run: |
          cd build/src
          clang++ -shared -o moo.dylib moo.hpp
          clang++ -shared -O3 -o mooO3.dylib moo.hpp
          clang++ -shared -O3 -Wall -Wextra -fvisibility=hidden -std=c++20 \
            -o mooO3WW20.dylib moo.hpp

          ls -lh moo.dylib

      - name: Copy Build Artifacts
        run: |
          mkdir -p artifact
          cp build/src/moo.dylib artifact/
          cp build/src/mooO3.dylib artifact/
          cp build/src/mooO3WW20.dylib artifact/
          ls artifact

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moo-SO-Artifacts-macos
          path: artifact/*.*

  test_unixbased:
    needs: unixbased
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        vector:
          - jobname: test-debian
            image: debian:latest
            os: ubuntu-latest
            cc: gcc
          - jobname: test-ubuntu
            image: ubuntu:latest
            os: ubuntu-latest
            cc: gcc
          - jobname: test-alpine
            image: alpine:latest
            os: ubuntu-latest
            cc: gcc
          - jobname: test-fedora
            image: fedora:latest
            os: ubuntu-latest
            cc: gcc
          - jobname: test-ubuntu-clang
            image: ubuntu:latest
            os: ubuntu-latest
            cc: clang
          - jobname: linux-sha256
            image: ubuntu:rolling
            cc: clang
          - jobname: linux-reftable
            image: ubuntu:rolling
            cc: clang
            cc_package: gcc-8
          - jobname: linux-breaking-changes
            cc: gcc
            image: ubuntu:rolling
          - jobname: linux-leaks
            image: ubuntu:rolling
            cc: gcc
          - jobname: linux-reftable-leaks
            image: ubuntu:rolling
            cc: gcc
          - jobname: linux-asan-ubsan
            image: ubuntu:rolling
            cc: clang
          - jobname: linux-meson
            image: ubuntu:rolling
            cc: gcc
          - jobname: linux-musl-meson
            image: alpine:latest
          # Supported until 2025-04-02.
          - jobname: pedantic
            image: fedora:latest
          # A RHEL 8 compatible distro.  Supported until 2029-05-31.
          - jobname: almalinux-8
            image: almalinux:8
          # Supported until 2026-08-31.
          - jobname: debian-11
            image: debian:11
    name: ${{ matrix.vector.jobname }} (${{ matrix.vector.os }})
    env:
      jobname: ${{ matrix.vector.jobname }}
      CI_JOB_OS: ${{ matrix.vector.os }}
      CC: ${{ matrix.vector.compiler }}
    steps:
      - uses: actions/checkout@v4

      - name: Test with ${{ matrix.vector.compiler }} on ${{ matrix.vector.os }}
        run: echo "Testing with ${{ matrix.vector.compiler }} on ${{ matrix.vector.os }}"

      - name: Run Tests
        run: |
          echo "Running tests for Moo on ${{ matrix.vector.os }} with ${{ matrix.vector.compiler }}"
          echo "Placeholder test: Always true"
          assert true, "Not implemented"
  

  test_windows:
    needs: windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Windows Tests
        shell: cmd
        run: |
          echo "Running tests for Moo on Windows"
          assert true, "This is a placeholder for actual tests"

  test_windows_api:
    needs: windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run API Tests
        shell: cmd
        run: |
          echo "Running API tests for Moo on Windows"
          assert true, "This is a placeholder for actual API tests"

  test_unixbased_api:
    needs: unixbased
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        vector:
          - jobname: test-debian
            image: debian:latest
            os: ubuntu-latest
            cc: gcc
          - jobname: test-ubuntu
            image: ubuntu:latest
            os: ubuntu-latest
            cc: gcc
          - jobname: test-alpine
            image: alpine:latest
            os: ubuntu-latest
            cc: gcc
          - jobname: test-fedora
            image: fedora:latest
            os: ubuntu-latest
            cc: gcc
          - jobname: test-ubuntu-clang
            image: ubuntu:latest
            os: ubuntu-latest
            cc: clang
          - jobname: linux-sha256
            image: ubuntu:rolling
            cc: clang
          - jobname: linux-reftable
            image: ubuntu:rolling
            cc: clang
            cc_package: gcc-8
          - jobname: linux-breaking-changes
            cc: gcc
            image: ubuntu:rolling
          - jobname: linux-leaks
            image: ubuntu:rolling
            cc: gcc
          - jobname: linux-reftable-leaks
            image: ubuntu:rolling
            cc: gcc
          - jobname: linux-asan-ubsan
            image: ubuntu:rolling
            cc: clang
          - jobname: linux-meson
            image: ubuntu:rolling
            cc: gcc
          - jobname: linux-musl-meson
            image: alpine:latest
          # Supported until 2025-04-02.
          - jobname: pedantic
            image: fedora:latest
          # A RHEL 8 compatible distro.  Supported until 2029-05-31.
          - jobname: almalinux-8
            image: almalinux:8
          # Supported until 2026-08-31.
          - jobname: debian-11
            image: debian:11
    name: ${{ matrix.vector.jobname }} (${{ matrix.vector.os }})
    env:
      jobname: ${{ matrix.vector.jobname }}
      CI_JOB_OS: ${{ matrix.vector.os }}
      CC: ${{ matrix.vector.compiler }}
    steps:
      - uses: actions/checkout@v4

      - name: Test API with ${{ matrix.vector.compiler }} on ${{ matrix.vector.os }}
        run: echo "Testing API with ${{ matrix.vector.compiler }} on ${{ matrix.vector.os }}"

      - name: Run API Tests
        run: |
          echo "Running API tests for Moo on ${{ matrix.vector.os }} with ${{ matrix.vector.compiler }}"
          assert true, "Not implemented"

  test_macos_api:
    needs: macos
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run MacOS API Tests
        run: |
          echo "Running API tests for Moo on MacOS"
          assert true, "This is a placeholder for actual API tests"

  test_macos:
    needs: macos
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run MacOS Tests
        run: |
          echo "Running tests for Moo on MacOS"
          assert true, "This is a placeholder for actual tests"

  packing_unixbased:
    needs: unixbased
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Unix Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: Moo-SO-Artifacts-*
          path: unix-artifacts

      - name: Pack Unix Artifacts
        run: |
          tar -czvf unix-artifacts.tar.gz -C unix-artifacts .
          ls -lh unix-artifacts.tar.gz

      - name: Upload Unix Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moo-SO-All-Unix
          path: unix-artifacts.tar.gz

  finishing:
    needs: [test_windows, test_unixbased, test_macos, test_windows_api, test_unixbased_api, test_macos_api]
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Finalize Build
        run: |
          echo "All tests completed successfully. Finalizing build."
          assert true, "This is a placeholder for finalization steps"

  docs:
    needs: finishing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Documentation
        run: |
          echo "Generating documentation for Moo"
          assert true, "This is a placeholder for documentation generation steps"