name: Compiling C++ Code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  config:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Nothing to configure
        shell: cmd
        run: |
          echo "No configuration needed for this job."

  windows:
    name: Windows+MSVC
    runs-on: windows-latest
    needs: config

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Build Environment
        shell: cmd
        run: |
          mkdir build
          xcopy src build\src /E /I /Y
          copy CMakeLists.txt build\

      - name: Compile C++ Code with CMAKE
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 ..
          cmake --build . --config Release

      - name: Copy Build Artifacts
        run: |
          cd ..
          mkdir artifact
          copy Moo\build\bin\Release\Moo.dll artifact\
          copy Moo\build\lib\Release\Moo.lib artifact\
          copy Moo\build\lib\Release\Moo.exp artifact\
          dir artifact
          pwd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moo-DLL-Artifacts
          path: D:\a\Moo\artifact

  windows_meson:
    name: Windows+Meson
    runs-on: windows-latest
    needs: config

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup Build Environment
        shell: cmd
        run: |
          mkdir meson
          xcopy src meson\src /E /I /Y
          copy meson.build meson\
          tree meson\src /F /A

      - name: Install Meson and Ninja
        shell: cmd
        run: |
          python -m pip install meson ninja

      - name: Setup
        shell: pwsh
        run: |
          cd meson
          meson setup src --vsenv -Dbuildtype=release

      - name: Compile
        shell: pwsh
        run: meson compile -C build

      - name: Copy Build Artifacts
        run: |
          mkdir artifact
          copy build\lib\Moo.dll artifact\
          dir artifact

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moo-DLL-Artifacts-Meson
          path: artifact\*

  docker_msvc:
    name: Docker Image for Windows+MSVC
    needs: windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: assert true, "This is a placeholder for Docker build steps"

  unixbased:
    needs: config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vector:
          - jobname: test-debian
            image: debian:latest
            os: ubuntu-latest
          - jobname: test-ubuntu
            image: ubuntu:latest
            os: ubuntu-latest
          - jobname: test-alpine
            image: alpine:latest
            os: ubuntu-latest
          - jobname: test-fedora
            image: fedora:latest
            os: ubuntu-latest
          - jobname: linux-sha256
            image: ubuntu:rolling
          - jobname: linux-reftable
            image: ubuntu:rolling
            cc_package: gcc-8
          - jobname: linux-breaking-changes
            image: ubuntu:rolling
          - jobname: linux-leaks
            image: ubuntu:rolling
          - jobname: linux-reftable-leaks
            image: ubuntu:rolling
          - jobname: linux-asan-ubsan
            image: ubuntu:rolling
          - jobname: linux-meson
            image: ubuntu:rolling
          - jobname: linux-musl-meson
            image: alpine:latest
          # Supported until 2025-04-02.
          - jobname: pedantic
            image: fedora:latest
          # A RHEL 8 compatible distro.  Supported until 2029-05-31.
          - jobname: almalinux-8
            image: almalinux:8
          # Supported until 2026-08-31.
          - jobname: debian-11
            image: debian:11
    name: ${{ matrix.vector.jobname }} (${{ matrix.vector.image }})
    container: ${{ matrix.vector.image }}
    env:
      jobname: ${{ matrix.vector.jobname }}
      
      CI_JOB_IMAGE: ${{ matrix.vector.image }}
    steps:
      - uses: actions/checkout@v4

      - name: Build on ${{ matrix.vector.image }}
        run: echo "Building on ${{ matrix.vector.image }}"

      - name: Update and Install Dependencies
        run: |
          if command -v apt-get > /dev/null; then
            apt-get update
            apt-get install -y build-essential cmake make ${{ matrix.vector.cc }}
            apt-get upgrade -y
          elif command -v apk > /dev/null; then
            apk add --no-cache build-base cmake make ${{ matrix.vector.cc }}
          elif command -v dnf > /dev/null; then
            dnf install -y gcc gcc-c++ cmake make clang
          fi

      - name: Setup Build Environment
        run: |
          mkdir -p build
          mkdir -p build/src
          cp -r src/* build/src/
          cp CMakeListsUNIX.txt build/CMakeLists.txt

      - name: Compile with CMake
        run: |
          cd build
          cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release .
          cmake --build . --config Release
          ls .

      - name: Copy Build Artifacts
        run: |
          mkdir -p artifact      
          cp build/lib/libMoo.so artifact/
          ls artifact

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moo-SO-Artifacts-${{ matrix.vector.jobname }}
          path: artifact/*.so

  macos:
    needs: config
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update and Install Dependencies
        run: |
          brew update
          brew upgrade
          brew install cmake
          xcode-select --install || true

      - name: Setup Build Environment
        run: |
          mkdir -p build
          cp -r src build/
          cp CMakeListsMacOS.txt build/CMakeLists.txt

      - name: Compile with CMake
        run: |
          cd build
          cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release .
          cmake --build . --config Release

      - name: Copy Build Artifacts
        run: |
          mkdir -p artifact
          cp build/lib/libMoo.dylib artifact/
          ls artifact

      - name: Debug Build Artifacts
        run: |
          echo "Debugging Moo dylib on macOS"
          otool -L artifact/libMoo.dylib
          nm -gU artifact/libMoo.dylib

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moo-Dylib-Artifacts-macos
          path: artifact/*.*

  test_unixbased_python:
    needs: unixbased
    runs-on: ubuntu-latest
    strategy:

      fail-fast: false
      matrix:
        vector:
          - jobname: test-debian
            image: debian:latest
            os: ubuntu-latest
          - jobname: test-ubuntu
            image: ubuntu:latest
            os: ubuntu-latest
          - jobname: test-alpine
            image: alpine:latest
            os: ubuntu-latest
          - jobname: test-fedora
            image: fedora:latest
            os: ubuntu-latest
          - jobname: linux-sha256
            image: ubuntu:rolling
          - jobname: linux-reftable
            image: ubuntu:rolling
            cc_package: gcc-8
          - jobname: linux-breaking-changes
            image: ubuntu:rolling
          - jobname: linux-leaks
            image: ubuntu:rolling
          - jobname: linux-reftable-leaks
            image: ubuntu:rolling
          - jobname: linux-asan-ubsan
            image: ubuntu:rolling
          - jobname: linux-meson
            image: ubuntu:rolling
          - jobname: linux-musl-meson
            image: alpine:latest
          # Supported until 2025-04-02.
          - jobname: pedantic
            image: fedora:latest
          # A RHEL 8 compatible distro.  Supported until 2029-05-31.
          - jobname: almalinux-8
            image: almalinux:8
          # Supported until 2026-08-31.
          - jobname: debian-11
            image: debian:11
    name: ${{ matrix.vector.jobname }} (${{ matrix.vector.os }})
    env:
      jobname: ${{ matrix.vector.jobname }}
      CI_JOB_OS: ${{ matrix.vector.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Download SO Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: Moo-SO-Artifacts-${{ matrix.vector.jobname }}

      - name: Create Runtime Environment
        run: | 
          mkdir runtime-${{ matrix.vector.api }}
          cp api/python/* runtime-${{ matrix.vector.api }}/
          cp Moo-SO-Artifacts-${{ matrix.vector.jobname }}/*.so runtime-${{ matrix.vector.api }}/

      - name: Run Python Tests
        run: |
          python3 runtime-${{ matrix.vector.api }}/test.py
          echo "Python tests completed successfully."

  test_windows:
    needs: windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Windows Tests
        shell: cmd
        run: |
          echo "Running tests for Moo on Windows"
          assert true, "This is a placeholder for actual tests"

  test_windows_api:
    needs: windows
    runs-on: windows-latest

    strategy:
      matrix:
        vector:
          - jobname: test-windows-api-python
            os: windows-latest
            api: python
            extension: .py
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download DLL
        uses: actions/download-artifact@v4
        with:
          name: Moo-DLL-Artifacts

      - name: Create Runtime Environment
        run: |
          mkdir runtime-${{ matrix.vector.api }}
          xcopy api\${{ matrix.vector.api }} runtime-${{ matrix.vector.api }} /E /I /Y
          copy Moo.dll runtime-${{ matrix.vector.api }}\      

      - name: Run Windows API Tests
        run: |
          ${{ matrix.vector.api }} runtime-${{ matrix.vector.api }}\test${{ matrix.vector.extension }}
  

  test_unixbased_api:
    needs: unixbased
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vector:
          - jobname: test-debian
            image: debian:latest
            os: ubuntu-latest
          - jobname: test-ubuntu
            image: ubuntu:latest
            os: ubuntu-latest
          - jobname: test-alpine
            image: alpine:latest
            os: ubuntu-latest
          - jobname: test-fedora
            image: fedora:latest
            os: ubuntu-latest
          - jobname: linux-sha256
            image: ubuntu:rolling
          - jobname: linux-reftable
            image: ubuntu:rolling
            cc_package: gcc-8
          - jobname: linux-breaking-changes
            image: ubuntu:rolling
          - jobname: linux-leaks
            image: ubuntu:rolling
          - jobname: linux-reftable-leaks
            image: ubuntu:rolling
          - jobname: linux-asan-ubsan
            image: ubuntu:rolling
          - jobname: linux-meson
            image: ubuntu:rolling
          - jobname: linux-musl-meson
            image: alpine:latest
          # Supported until 2025-04-02.
          - jobname: pedantic
            image: fedora:latest
          # A RHEL 8 compatible distro.  Supported until 2029-05-31.
          - jobname: almalinux-8
            image: almalinux:8
          # Supported until 2026-08-31.
          - jobname: debian-11
            image: debian:11
        testvector:
          - jobname: test-windows-api-python
            api: python3
            extension: .py
    name: ${{ matrix.vector.jobname }} (${{ matrix.vector.os }})
    env:
      jobname: ${{ matrix.vector.jobname }}
      CI_JOB_OS: ${{ matrix.vector.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Download SO Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: Moo-SO-Artifacts-${{ matrix.vector.jobname }}

      - name: Create Runtime Environment
        run: | 
          mkdir runtime-${{ matrix.vector.api }}
          cp api/${{ matrix.testvector.api }}/* runtime-${{ matrix.vector.api }}/
          cp Moo-SO-Artifacts-${{ matrix.vector.jobname }}/*.so runtime-${{ matrix.vector.api }}/

      # TODO: Conducting TESTs

  test_macos_api:
    needs: macos
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run MacOS API Tests
        run: |
          echo "Running API tests for Moo on MacOS"
          assert true, "This is a placeholder for actual API tests"

  test_macos:
    needs: macos
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run MacOS Tests
        run: |
          echo "Running tests for Moo on MacOS"
          assert true, "This is a placeholder for actual tests"

  packing_unixbased:
    needs: unixbased
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Unix Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: Moo-SO-Artifacts-*
          path: unix-artifacts

      - name: Pack Unix Artifacts
        run: |
          tar -czvf unix-artifacts.tar.gz -C unix-artifacts .
          ls -lh unix-artifacts.tar.gz

      - name: Upload Unix Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moo-SO-All-Unix
          path: unix-artifacts.tar.gz

  finishing:
    needs: [ test_windows, test_unixbased_python, test_macos, test_windows_api, test_unixbased_api, test_macos_api ]
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Finalize Build
        run: |
          echo "All tests completed successfully. Finalizing build."
          assert true, "This is a placeholder for finalization steps"

  docs:
    needs: finishing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Documentation
        run: |
          echo "Generating documentation for Moo"
          assert true, "This is a placeholder for documentation generation steps"